version: 1.0

snow:
  - id: 570216 # Milo DC
  - source_path:
    - exclude:
      - '.github/**'
      - 'edgeworkers/**'
notifications:
  jira:
    default:
      project: MWPW # Mandatory
      filters:
        include:
          risk_rating: R5
      fields:
        assignee:
          name: gunn
        customfield_11800: MWPW-140779 #epic link
        customfield_12900:
          value: Slytherin
        watchers:
          - casalino
          - jmichnow
          - mauchley
          - tsay
          - joaquinrivero
        labels:
          - "OriginatingProcess=Kodiak"
          - "security"
          - "kodiak-ticket"
          - "dc-security"
        components:
          - name: "DevOps Security"
